<?php
/**
 * Created by Brander
 * Based on Module from "Magentix" (https://github.com/magentix/Fee)
 *
 * @category   Brander
 * @package    Brander_PaymentFee
 * @author     Roman Shopin (roman.s@devromans.com)
 * @license    This work is free software, you can redistribute it and/or modify it
 */
?>

<?php if($this->getSource() instanceof Mage_Sales_Model_Order): ?>
    <?php if ((float)$this->getSource()->getFeeAmountRefunded() > 0): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('payment_fee')->__('Fee refunded to customer') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getFeeAmountRefunded(); ?></strong></td>
        </tr>
    <?php endif; ?>
<?php else: ?>
    <?php if ((float)$this->getSource()->getFeeAmount()): ?>
        <tr>
            <td class="label"><strong><?php echo Mage::helper('payment_fee')->__('Fee Refunded') ?></strong></td>
            <td><strong><?php echo $this->getSource()->getFeeAmount(); ?></strong></td>
        </tr>
    <?php endif;  ?>
<?php endif; ?>

